### ISSUE TITLE
Disappearing or Stale Username Displayed

### ISSUE THREAD

**Issue by revjtanton** [CodeForBaltimore/Healthcare-Rollcall#102]
### User Story
As an end-user
I'd like to consistently see my username on all pages
So that I can interact with the page consistently.

### Acceptance Criteria
- [x] Username no longer disappears (unable to recreate except when logging in for the first time or after clearing history)
- [x] When switching to a new user, and logging in, my username is displayed properly.  It currently shows the previous username.
- [x] After clearing my history, my username should not be blank when I log in
- [x] PR merged to `master`

### Notes
See msmith125's comment from 5/12/2020 for details and screenshots of system's behavior with the username display.

**Comment by helro154** [comment]
I'm not sure if this is still an issue. I was able to view my username. 

![image](https://user-images.githubusercontent.com/5619637/79253387-1f409b80-7e51-11ea-8d97-a04af78a0b47.png)

**Comment by msmith125** [comment]
This is no longer an issue.  I was able to go to all pages of the application and the username appeared on the upper right corner of all pages.

**Comment by revjtanton** [comment]
Didn't see the ticekt for this when I fixed it.
