### ISSUE TITLE
Add Export to CSV button to allow a user to export Facilities

### ISSUE THREAD

**Issue by blakenan-bellese** [CodeForBaltimore/Healthcare-Rollcall#108]
### User Story
As a user of Healthcare Roll Call, I would like to have the ability to Export Facility Data to a .csv file so that I can quickly review and store data from the system. 

### Acceptance Criteria
- [ ] Allow user to select "Export to CSV"
- [ ] All users can export, no disable/denial message
- [ ] Browser file DL initiated (browser displays progress/failure/etc)
- [ ] 508 compliance, please
- [ ] Indicate number of total facilities across all pages

### Notes
Eventually the goal will be to have many exports, which is supported by the API.  This story address the export of facilities.

**Comment by joshglazer** [comment]
This has been completed.
