### ISSUE TITLE
Display current role to user

### ISSUE THREAD

**Issue by blakenan-bellese** [CodeForBaltimore/Healthcare-Rollcall#109]
### User Story
As a user of Healthcare RollCall, I would like to have my current role displayed, so that I know my security level.

### Acceptance Criteria
- [ ] The current role of the user is displayed next to or under their userid on each page of the system.
- [ ] All documentation is reviewed to ensure that user levels are documented accurately.
- [ ] PR merged to `master`

### Notes
related to issue #100 - Adding Security, which has been closed.

**Comment by helro154** [comment]
I'm not sure if this is still an issue. I was able to see the username. 
![image](https://user-images.githubusercontent.com/5619637/79253158-c113b880-7e50-11ea-8ae0-2848a19985cd.png)
