### ISSUE TITLE
Adding contact information, Email Address & Phone #, shows duplicate records.

### ISSUE THREAD

**Issue by carorm** [CodeForBaltimore/Healthcare-Rollcall#117]
### User Story
As an end-user
I'd like to consistently see contact information displayed accurately on the Facility Check-in page So that I can interact with the page consistently.

### Acceptance Criteria
- [ ] Contact Email Address no longer duplicates
- [ ] Contact Phone Number no longer duplicates
- [ ] PR merged to `master`

### Notes
Details of how to recreate issue are in comments, both a video and a pdf  - IssueDetails117.pdf

**Comment by carorm** [comment]
[Video](https://drive.google.com/file/d/1ASmcMMBajaJVQsvuWlvp_KxL0iL79PE3/view) of it as well from Bill

**Comment by msmith125** [comment]
I was able to recreate this on 5/12/2020.  Attached are the steps I followed to recreate and some screen shots of the errors.  Note that the behavior is different if you create the entity with name and email versus name, email and phone.

[IssueDetails117.pdf](https://github.com/CodeForBaltimore/Healthcare-Rollcall/files/4617742/IssueDetails117.pdf)
