### ISSUE TITLE
Enforce User Access on the Front End

### ISSUE THREAD

**Issue by Ejones20** [CodeForBaltimore/Healthcare-Rollcall#119]
### User Story
As a user
I need the front end to enforce the permissions from the API 
So that I have the appropriate permissions when I login

### Acceptance Criteria
- [x] Verify that when a user logs in as a user, they have the appropriate permissions (see spreadsheet below)
- [x] Verify that when a user logs in as an admin, they have the appropriate permissions (see referenced spreadsheet below)
- [x] Verify that front end enforces the user roles according to the permissions granted from the API. (see spreadsheet below)

### Notes
[User Roles](https://drive.google.com/open?id=158hmPJXm3DbltLOmnkF-xL7lM036hbkyNcdidAPhX4U)

**Comment by Ejones20** [comment]
[User Rolls Doc](https://drive.google.com/open?id=158hmPJXm3DbltLOmnkF-xL7lM036hbkyNcdidAPhX4Uurl)

**Comment by Ejones20** [comment]
[User Roles](https://drive.google.com/open?id=158hmPJXm3DbltLOmnkF-xL7lM036hbkyNcdidAPhX4U)

**Comment by Ejones20** [comment]
Unsure of how to decifer user (homer) as Admin or User

**Comment by revjtanton** [comment]
I did this without realizing there was a ticket in for it.
