### ISSUE TITLE
Add a Contact to a Single Entity

### ISSUE THREAD

**Issue by Ejones20** [CodeForBaltimore/Healthcare-Rollcall#120]
### User Story
As a user
I'd like the front end to support the functionality of the API
So that I can enter a contact to an entity. 

### Acceptance Criteria
- [x] Verify the user is able login using credentials and access the Dashboard.
- [x] Verify the user is to Filter and search for a provider and click on the desired provider from the Dashboard 
- [x] Verify the user is able to scroll and click on the desired provider from the Dashboard. 
- [x] Verify the user is able to access the Facility Checkin page.
- [x] Verify the user is able to click 'Add Contact' to create a single contact from the Facility 
        Checkin page, including Name, Phone number and email.
- [x] Verify the user is able to click 'Create Contact' or 'Cancel.'
- [x] Verify the user is able to Click 'Return to the Dashboard.'

**Comment by Ejones20** [comment]
This is working as the documented above.

**Comment by msmith125** [comment]
Validated that All AC have been satisfied.
