### ISSUE TITLE
Update and Associate Existing Contact to Facility Checkin

### ISSUE THREAD

**Issue by Ejones20** [CodeForBaltimore/Healthcare-Rollcall#121]
### User Story
As a user within an Entity
I'd like to update and associate an existing contact from the Facility Checkin
So that I can reduce the number of times the information must be entered. 

### Acceptance Criteria
- [ ] Verify the user is able login using credentials and access the Dashboard.
- [ ] Verify the user is to search for and click on the desired provider from the Dashboard. 
- [ ] Verify the user is able to access the Facility Checkin page.
- [ ] Verify the user is able to Click 'Add Contact' to create a single contact from the Facility Checkin page. 
- [ ] Verify the user is able to enter the Name, Phone number, and Email. 
- [ ] Verify the user is able to click 'Create Contact' or 'Cancel'
- [ ] Verify the user is able to Update an Existing Contact from the Facility Check in page. 
- [ ] Verify the user is able to Associate the Existing Contact to the Entity.
- [ ] Verify the user is able to Disassociate an Existing Contact from the Entity. 
- [ ] Verify the user is able to Create and Associate New Contact Notes and Dialog. 
- [ ] Verify the user is able to click 'Return to the Dashboard'

### Notes
1 - Backend - when user POSTS contact or entity, 
DELETE only applicable to admin roles.

**Comment by blakenan-bellese** [comment]
@Ejones20 Looks good.  One suggestion...  I'm thinking that we should also check the following scenario.  If a single contact is associated with two facilities, an update to that contact is reflected on both facilities' contact lists.
