### ISSUE TITLE
Many to Many - Associate Existing Contacts and Entities

### ISSUE THREAD

**Issue by Ejones20** [CodeForBaltimore/Healthcare-Rollcall#122]
### User Story
As a user 
I'd like to enter a new Entity or Contact 
So that I can I make an association between the two

### Acceptance Criteria
- [X] Verify the user is able login using credentials and access the Dashboard.
- [X] Verify the user is to search for and click on the desired provider from the Dashboard.
- [X] Verify the user is able to access the Facility Checkin page from the Dashboard. 
- [X] Verify the user is able to enter Checkin responses on the Checkin Page. 
- [X] Verify the user is able to associate an Existing Facility(Entity) to an Existing Contact. 
- [X] Verify the system associates the new contact dialog to an existing contact. 
- [X ] Verify the user is able to associate an Existing contact to an Existing Facility. 
- [X] Verify the user is able to Create a new Contact from the Facility Details and enter new notes and dialog.

### Notes
2 -Separate Facility Checkin, then associate contact information.

**Comment by msmith125** [comment]
Functionality defined in AC has been verified.  Separate story will be created for allowing users to create Facilities using the front-end.
