### ISSUE TITLE
Add name and email to the unlink/delete contact confirmation dialogs.

### ISSUE THREAD

**Issue by msmith125** [CodeForBaltimore/Healthcare-Rollcall#142]
### User Story
As a user of the HealthCare RollCall UI
I'd like to see the Contact Name and Email in addition to the id when I Unlink/Delete a Contact
So that I have more information when confirming the Unlink/Delete

### Acceptance Criteria
- [ ] The Unlink Confirmation message (see example in Notes) contains the Contact Name and Email
- [ ] The Unlink Confirmation message (see example in Notes) contains the UUID
- [ ] The Delete Confirmation message (see example in Notes) contains the Contact Name and Email
- [ ] The Delete Confirmation message (see example in Notes) contains the UUID
- [x] PR merged to `master`

### Notes
Currently the UUID is the only identifying element on the Unlink/Delete Confirmation message.  Name and email should be added.  UUID is not necessary but could stay.

Here is an example message:
![image](https://user-images.githubusercontent.com/58228205/81984076-47fbb280-9602-11ea-9566-6b921d04e1ad.png)

**Comment by joshglazer** [comment]
https://github.com/CodeForBaltimore/Healthcare-Rollcall/pull/208

**Comment by joshglazer** [comment]
I've addressed this in https://github.com/CodeForBaltimore/Healthcare-Rollcall/pull/208
