### ISSUE TITLE
Move the address of the Facility from under the Contact Information to Under the Facility Name

### ISSUE THREAD

**Issue by msmith125** [CodeForBaltimore/Healthcare-Rollcall#143]
### User Story
As a user of the HealthCare RollCall UI
I'd like to have the Facility address moved from Under "Contact Information" to Under the Facility Name
So that I am not confused by the address and understand that it is the address of the Facility, not the address of the Contact

### Acceptance Criteria
- [ ] Facility address is no longer under Contact Information on the Facility Check-In page
- [ ] Facility address is under the Facility Name on the Facility Check-In page
- [ ] Contacts are still listed under Contact Information on the Facility Check-In page
- [ ] PR merged to `master`

### Notes
Here is an example of what it currently looks like.  The address under "Contact Information" should be moved to under the Facility Name:
![image](https://user-images.githubusercontent.com/58228205/81984894-7af27600-9603-11ea-88be-b13d32c7c96c.png)

**Comment by joshglazer** [comment]
I'm closing this issue, it seems like it has already been completed
