### ISSUE TITLE
Editing a contact and changing the email address to an empty field should give message that field cannot be empty and this message should be readable

### ISSUE THREAD

**Issue by msmith125** [CodeForBaltimore/Healthcare-Rollcall#145]
### User Story
As a user of the HealthCare RollCall UI
I'd like to see an error message and stay on the Update Contact page when an empty email address is entered
So that I can understand that this is a required field

### Acceptance Criteria
- [ ] Verify that a contact's email address can be updated on the Update Contact Page when the email address is valid.
- [ ] Verify that the updated email address is persisted on the Facility Check-In Page
- [ ] Verify that an appropriate error message is displayed when an invalid email address is entered (no @ example test-google.com)
- [ ] Verify that the email address field cannot be updated to be empty and if it is, an error message is displayed and you stay on the Update Contact page.
- [ ] PR merge to `master`

### Notes
When you edit a contact's email to a valid email address, it updates successfully.  This is good.
When you edit a contact's email to an invalid email address (no @), an error is displayed.  This is good.
When you edit a contact's email to an empty field, you see a little red message under the email but are not given time to read it before being sent back to the Facility Check-In page.  If you try to click "Update Contact" with an empty email address, error should be displayed and you should not move from the Update Contact Page.

**Comment by revjtanton** [comment]
A contact isn't required to have an email address. We need it to be possible to list just a name and role for individuals who don't want their phone or email listed, but are still a point of contact at the facility.
