### ISSUE TITLE
Do not display Facility's without Name on the Provider Status Dashboard

### ISSUE THREAD

**Issue by msmith125** [CodeForBaltimore/Healthcare-Rollcall#146]
### User Story
As a user of the HealthCare RollCall UI
I'd like to prevent Facilities without Names from existing on the Provider Status Dashboard
So that there are not a lot of empty spaces on the Provider Status Dashboard (see image in Notes)

### Acceptance Criteria
- [ ] Verify that a Facility without a name does not display on the Provider Status Dashboard
- [ ] PR merged to `master`

### Notes
The best approach with the least impact to BMoreResponsive is to not display Facilities without a Name through a UI update.  Another option would be to alter BMoreResponsive to make certain fields required.

![image](https://user-images.githubusercontent.com/58228205/81988300-35d14280-9609-11ea-8cca-7b6df6e6d4e0.png)

**Comment by revjtanton** [comment]
This is a data entry issue. No data should be in the system without a name like that.
