### ISSUE TITLE
Password persists on Login Page even when you change username

### ISSUE THREAD

**Issue by msmith125** [CodeForBaltimore/Healthcare-Rollcall#150]
### User Story
As a User of the HealthCare RollCall UI
I'd like to have my password removed from the Login Page when I logout 
So that I can feel secure using the UI

### Acceptance Criteria
- [ ] Verify that when you first hit the Login Page, the Password field is blank
- [ ] Verify that when you log out, the Password field is blank
- [ ] PR merged to `master`

### Notes
Here is image - I logged out and changed my userid and did not have to enter password:
![image](https://user-images.githubusercontent.com/58228205/81994122-2657f680-9615-11ea-8359-fccb13ee60a1.png)

**Comment by revjtanton** [comment]
I don't think this is an issue with the application. I am not able to replicate it. I think it's browser-specific, and user-specific. It looks like the browser's cached credentials. This can be turned off in the browser settings.
