### ISSUE TITLE
Display All Contact/Facility relationships so Users can make informed decisions when deleting Contacts

### ISSUE THREAD

**Issue by msmith125** [CodeForBaltimore/Healthcare-Rollcall#151]
### User Story
As a User of the HealthCare RollCall UI
I'd like to know which Facilities a Contact is linked to before I delete the Contact
So that I can make informed decisions 

### Acceptance Criteria
- [ ] Verify that all Facilities associated with the Contact are listed on the "Contact Information Page"
- [ ] Verify the list of Facilities is accurate
- [ ] Verify the list of Facilities changes when Contact/Facility link are made/removed
- [ ] PR merged to `master`

### Notes
Here are wireframes which show some options for displaying Facility's/Contacts
https://www.figma.com/file/tjhV8ueayBrTeuqnzKN0EH/Healthcare-Roll-Call

**Comment by joshglazer** [comment]
I accidentally wrote some code that fits this acceptance criteria.  I've linked the pull request #209 to this issue.  I also made a similar change to the facility page, to show all contacts.
