### ISSUE TITLE
Update user role to support facility self check-in - outreach coordinator (existing user role)

### ISSUE THREAD

**Issue by msmith125** [CodeForBaltimore/Healthcare-Rollcall#157]
### User Story
As a developer of the HealthCare Roll Call UI
I'd like to update the user role, which is used by  outreach coordinators
So that I can support facility self check-in securely

### Acceptance Criteria
- [x] Outreach coordinator (user role) will have appropriate access to send emails to facilities
- [x] Outreach coordinator (user role) will have appropriate access to view results of self-checkins
- [x] Outreach coordinator (user role) will have appropriate access to export results of self-checkins
- [ ] Outreach coordinator (user role) will have appropriate access to view email metrics (number sent, number replied to, number bounced back, number not replied to, ....)
- [x] Outreach coordinator (user role) will not have access to all functionality (editing contacts?....)
- [ ] Outreach coordinator (user role) will also have access shown below in image
- [ ] PR merged to `master` 

### Notes
Story #155 contains further detail about the Outreach Coordinator.
Story #153 contains further detail about the Outreach Coordinator and the emails sent to Facilities.  

![image](https://user-images.githubusercontent.com/58228205/82322036-d629bd00-99a3-11ea-994b-e9b512f2dc3d.png)

**Comment by blakenan-bellese** [comment]
@msmith125 A couple comments:
- The "Edit email template" capability does not yet exist.  I think we should save this for Self-checkin v2 milestone.   If that make sense, can you created a milestone with this story to cover both the functionality and security around it?
- This "user" role that currently exists is being used by the outreach coordinators. We may want to indicate that this story is not a new role, but rather a clarification and name change.  Would that make sense?
- There is a spreadsheet of permissions (I'll slack you a link) that you can reconcile against to align on the limitations of this role.
