### ISSUE TITLE
Password Requirements

### ISSUE THREAD

**Issue by msmith125** [CodeForBaltimore/Healthcare-Rollcall#168]
### User Story
As an admin user
I'd like to understand the password requirements
So that I can create users using the Bmore Responsive Enpoints

### Password Requirements
minimum of 8 characters
1 uppercase
1 lowercase
1 special
1 digit

### Acceptance Criteria
- [ ] When user is attempted to be created with a password that does not meet the above requirements, a message is returned indicating the requirements
- [ ] Swagger doc is updated to indicate the requirements
- [ ] Postman is updated 
- [ ] PR merged to master

### Notes
This is related to bmore responsive issue 173

**Comment by mpiroc** [comment]
CodeForBaltimore/Bmore-Responsive#173
