### ISSUE TITLE
Dockerize all the things!

### ISSUE THREAD

**Issue by revjtanton** [CodeForBaltimore/Healthcare-Rollcall#20]
### User Story
As a developer
I'd like to Dockerize this project
So that I can use Docker.

### Acceptance Criteria
- [x] Dockerfile created
- [ ] PR merged to `master`

**Comment by jbixon13** [comment]
@revjtanton Are we looking to build an automated docker CI/CD pipeline to Heroku? I can use the shiny pipeline I built as a template for that using Travis so I can take that ticket as well

**Comment by revjtanton** [comment]
Yes, ideally. We have to figure out what we're doing with the database though. We can cross that bridge when we get there.
