### ISSUE TITLE
Dockerize entire solution 

### ISSUE THREAD

**Issue by blakenan-bellese** [CodeForBaltimore/Healthcare-Rollcall#201]
### User Story
As a new team member
I'd like to spin up Bmore Responsive and Healthcare Rollcall easily
So that I can explore and test the solution

### Acceptance Criteria
- [ ] `docker-compose` results in Healthcare Rollcall  front end being accessible @ http://localhost:8080

### Notes
We have many new, transient team members offering to help with the project.  Since we have no shard test environment, it is imperative that new team members can spin up our solution quickly.  A docker solution limits dependency on local machine which is unpredictable and can be hard to debug for folks not familiar with node/vue solutions.

**Comment by phillipjf** [comment]
@blakenan-bellese Can we consider this closed per #205 ?

**Comment by blakenan-bellese** [comment]
Closed based on #205
