### ISSUE TITLE
Setup database

### ISSUE THREAD

**Issue by revjtanton** [CodeForBaltimore/Healthcare-Rollcall#21]
### User Story
As a developer
I'd like to have a PostgreSQL database to work with
So that I can develop a data-driven application

### Acceptance Criteria
- [ ] database diagram added to docs
- [x] any applicable code added 
- [ ] Docker solution put in place
- [x] PR merged to `master` if applicable

### Notes
Docker is not _required_ but **strongly** suggested.

**Comment by ao10** [comment]
Should we use the Docker official image of Postgres?

https://hub.docker.com/_/postgres

**Comment by revjtanton** [comment]
@ao10 yes
