### ISSUE TITLE
Create a login screen

### ISSUE THREAD

**Issue by revjtanton** [CodeForBaltimore/Healthcare-Rollcall#24]
### User Story
As a user
I'd like to be presented with a login screen
So that I can securely login to the application

### Acceptance Criteria
- [ ] A login page is created with VueJS
- [ ] A user can login using credentials
- [ ] PR merged to `master`

### Notes
Dependant on #19 #21 #23

**Comment by joffutt4** [comment]
@revjtanton did we want to keep this open for when full login functionality is implemented? Or should we close it with the basic login page having been created?

**Comment by revjtanton** [comment]
> @revjtanton did we want to keep this open for when full login functionality is implemented? Or should we close it with the basic login page having been created?

I'm in favor of two tickets for this. We can consider this closed. We'll need a new ticket to implement the user API when that's ready. Should be soon.
