### ISSUE TITLE
Support for multi-line factility notes

### ISSUE THREAD

**Issue by blakenan-bellese** [CodeForBaltimore/Healthcare-Rollcall#240]
### User Story
As a outreach coordinator
I'd like to record status updates and short notes
So that I can ensure that other coordinators have the most accurate up-to-date picture on facility needs/status

### Acceptance Criteria
- [ ] The Notes field on the facility edit page ("/facility/edit/<id>") should allow multi line text text entry, similar to the multiline text entry permitted for some of the check in responses. 
- [ ] Pre-existing multi-line text values should be displayed with the line feeds as originally entered.
- [ ] The Notes field should be sized to display 5 lines of text and be scrollable when more text exists (for both edit page and facility view page)

### Notes
This issue assumes that the existing API functionality and JSON payloads can handle multiline notes as-is.  If this is NOT true, please create an issue in Bmore-Responsive to add multi-0line support on back end.

**Comment by c-malecki** [comment]
Question before submitting a PR for this issue:

5 lines of text - Should Notes on the view side, not just the form field, also have a `max-height` that limits to 5 lines of text with a Y scroll?
![snippet](https://user-images.githubusercontent.com/50671267/104537787-a1304180-55e8-11eb-977a-8056ab14d7fa.png)

**Comment by blakenan-bellese** [comment]
Chris,
       Great question…  Answer is yes.  Thanks for the help. Truly appreciated.
[cid:image001.png@01D6EA50.01EF94D0]

Bill Lakenan | Agile Coach
Bellese Technologies | bellese.io
blakenan@bellese.io<mailto:blakenan@bellese.io>  |  443-914-2126
300 Red Brook Blvd, Owings Mills, MD 21117
[https://lh3.googleusercontent.com/-l-MSfbYFAnCvqklJE30UrLFPpNrtvIWKu3Y-7b8YfHhjFo5eLZjcMtoctL7cl6EWWc1MBBdxdfmf0w2fXGodEWk01bd6RtrvBC1LqjAYbvItinODkiEPVjeIYKSHJap3qwIxjsM]<https://www.linkedin.com/company/2705760/> [https://lh4.googleusercontent.com/QNJbiLeSHzDK4DPi0QCoSi7jcoWfVnDUMUPCVXm86rk_4iRu8RasvhalLLiXNE7EqHEp8ARRWItZQ8PSIB4Np7HFC520sEBYwbUCE4as5ykVcog22WWDeJQesZDEAd14u3MubYPs] <https://www.facebook.com/Bellese-Technologies-490279364472269>
