### ISSUE TITLE
User Dashboard

### ISSUE THREAD

**Issue by revjtanton** [CodeForBaltimore/Healthcare-Rollcall#25]
### User Story
As an end user 
I'd like to see a dashboard when I login
So that I can be presented with relevant info

### Acceptance Criteria
- [x] dashboard system code created
- [x] dashboard page present when user logs in
- [x] PR merged to `master`

### Notes
Dependant on #24

**Comment by c-malecki** [comment]
I would be happy to take this.

**Comment by revjtanton** [comment]
> I would be happy to take this.

Sounds great! We'd like to implement GoldenLayout for the dashboard portion of this https://golden-layout.com/

There is a Vue package to get started with here: https://github.com/emedware/vue-golden-layout

I've added you to the org and to the team. When you accept I'll assign this issue to you. Thanks @c-malecki !

**Comment by revjtanton** [comment]
Also keep in mind we'll be pulling the data from the Bmore-Responsive API which hasn't deployed yet, and which doesn't have all of the endpoints built out yet. For now you may need to use hardcoded dummy data or get with us on Slack and we'll try to coordinate backend/frontend dev.

**Comment by c-malecki** [comment]
Sounds good. I can set up just calls to a substitute API for functionality's sake until the Bmore-Responsive API is available. I will also look at GoldenLayout. 

Is there any current fleshed out idea of what the dash will display depending on which user type is logged in? I see that the example_data.xlsx has what I assume will be the data stored within the Bmore-Responsive API.

**Comment by revjtanton** [comment]
We're still in a research phase for a lot of that, so we're really working on placeholders across the board. I'll add you to the research room on Slack.

**Comment by revjtanton** [comment]
We should implement this:
https://github.com/emedware/vue-golden-layout
https://golden-layout.com/

**Comment by revjtanton** [comment]
We have a dashboard that has been implemented. Should we close this ticket and then open new ones to update and flush out more content on the dashboard?

**Comment by funkybunch** [comment]
@revjtanton Thats my vote.
