### ISSUE TITLE
Multi-repo docker-compose

### ISSUE THREAD

**Issue by jbixon13** [CodeForBaltimore/Healthcare-Rollcall#37]
### User Story
As a developer
I'd like to have docker-compose set up
So that I can set up and build in a single environment 

### Acceptance Criteria
- [x] one command set up for local development 
- [x] backend, frontend, db services can communicate

**Comment by revjtanton** [comment]
our API repo is here: https://github.com/CodeForBaltimore/Bmore-Responsive

**Comment by jbixon13** [comment]
https://github.com/CodeForBaltimore/Bmore-Responsive/pull/28
