### ISSUE TITLE
User page

### ISSUE THREAD

**Issue by revjtanton** [CodeForBaltimore/Healthcare-Rollcall#47]
### User Story
As an end user
I'd like to have a contact page
So that I can see details about an individual contact

### Acceptance Criteria
- [ ] contact page created
- [ ] contact page pulls from API
- [ ] PR merged to `master`

### Notes
The contact endpoints are live in `master` on Bmore-res

**Comment by revjtanton** [comment]
Should this be closed like the dashboard ticket and we'll open new tickets to add new content?

**Comment by funkybunch** [comment]
@revjtanton I think this is still applicable.  The entity page will list contacts and then they can click on specific contacts to review that information.  I could see this taking the form of a page or a modal.  Either of which should resolve this ticket.

**Comment by helro154** [comment]
hey i'd like to help with this one, but looks like this is done with the facility page. please confirm, if not, i'll take a look at it.

**Comment by funkybunch** [comment]
@Helro154 yes, looks like this one should have been closed.

**Comment by funkybunch** [comment]
Initially created by #78
