### ISSUE TITLE
Check-in functionality

### ISSUE THREAD

**Issue by revjtanton** [CodeForBaltimore/Healthcare-Rollcall#48]
### User Story
As an end user
I'd like to have check-in functionality
So that I can check-in facilities during an emergency

### Acceptance Criteria
- [x] check-in functionality built into dashboard
- [x] ability to take notes, and track other stats, via dashboard
- [x] PR merged to `master`

### Notes
This functionality is not currently ready from Bmore-res. Will update ticket when available.

**Comment by funkybunch** [comment]
Pulling this in to work on it today

**Comment by funkybunch** [comment]
Resolved by #67
