### ISSUE TITLE
Guiding language on current UI

### ISSUE THREAD

**Issue by revjtanton** [CodeForBaltimore/Healthcare-Rollcall#68]
### User Story
As an end user
I'd like to have clear instruction and verbiage instructing use
So that I can use the app effectively

### Acceptance Criteria
- [x] User are able to use the product effectively without guidance

### Notes
We have a meeting scheduled for Saturday at 5pm.

**Comment by uxstephanie** [comment]
https://docs.google.com/presentation/d/1J0E85xYGEG00avCAFarUmB5t_G8OWMyn7qDT2J6mBP8/edit?usp=sharing
